### ISSUE TITLE
Not Found - Broken URL

### ISSUE THREAD

**Issue by scramble45** [Kazade/dreampi#11]
Not sure if this is the right place for this. But this URL looks like its broken.
[https://dreamcast.online/dreampi/dreampi_dns.conf](https://dreamcast.online/dreampi/dreampi_dns.conf)

**Comment by Kazade** [comment]
Hi! Yes that's kind of intentional. That's a backup if anything ever happens to my DNS server (e.g the IP address changes). I did originally intended to put a file there, so that the DNS server would become a fallback, but I'm worried it might break something (it's not tested) so I thought it better to leave it as an emergency thing.

**Comment by scramble45** [comment]
Thanks for explaining.
